[project]
src = "src"
out = "out"
dot_env = ".env"
dependencies = ["snekmate"]

[networks.pyevm]
is_zksync = false

[networks.arbitrum-sepolia]
url = "https://sepolia-rollup.arbitrum.io/rpc"
chain_id = 421614
save_to_db = true
