[project]
src = "src"
out = "out"
dot_env = ".env"
dependencies = ["snekmate"]

[networks.pyevm]
is_zksync = false

[networks.base]
url = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
chain_id = 8453
block_identifier = "safe"
save_to_db = true
explorer_uri = "https://base.blockscout.com/"
explorer_type = "blockscout"
explorer_api_key = "${BLOCKSCOUT_API_KEY}"

[networks.base-fork]
url = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
chain_id = 8453
block_identifier = "safe"
save_to_db = false
fork = true

[networks.base.contracts]
usdc = { address = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913" }
fluid_fusdc = { address = "0xf42f5795D9ac7e9D757dB633D693cD548Cfd9169" }

# Moccasin does not inherit contracts from `base`; keep these in sync.
[networks.base-fork.contracts]
usdc = { address = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913" }
fluid_fusdc = { address = "0xf42f5795D9ac7e9D757dB633D693cD548Cfd9169" }
